import express from "express";
import { GoogleGenAI } from "@google/genai";
import { insertBooking, isSlotTaken, listBookings, findBooking, rescheduleBooking, cancelBooking } from "./db";
import { sendBookingEmails } from "./email";

const app = express();

app.use(express.json({ limit: "50mb" }));

// Lazy init Gemini AI
let aiClient: GoogleGenAI | null = null;

function getAiClient(): GoogleGenAI {
  if (!aiClient) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY environment variable is missing.");
    }
    aiClient = new GoogleGenAI({
      apiKey: apiKey,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });
  }
  return aiClient;
}

// Image Generation API Endpoint
app.post("/api/generate-image", async (req, res) => {
  try {
    const { prompt, size = "1K", aspectRatio = "1:1" } = req.body;

    if (!prompt || typeof prompt !== "string") {
      return res.status(400).json({ error: "A valid prompt string is required" });
    }

    const ai = getAiClient();

    // High quality image generation with gemini-3-pro-image-preview
    // Size options: 1K, 2K, 4K
    const validSizes = ["1K", "2K", "4K"];
    const finalSize = validSizes.includes(size) ? size : "1K";

    const response = await ai.models.generateContent({
      model: "gemini-3-pro-image-preview",
      contents: {
        parts: [{ text: prompt }],
      },
      config: {
        imageConfig: {
          imageSize: finalSize,
          aspectRatio: aspectRatio || "1:1",
        },
      },
    });

    let imageUrl: string | null = null;
    let descriptionText: string | null = null;

    if (response.candidates && response.candidates[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          const base64Data = part.inlineData.data;
          const mimeType = part.inlineData.mimeType || "image/png";
          imageUrl = `data:${mimeType};base64,${base64Data}`;
        } else if (part.text) {
          descriptionText = part.text;
        }
      }
    }

    if (!imageUrl) {
      return res.status(500).json({
        error: "No image generated by the AI model.",
        text: descriptionText,
      });
    }

    return res.json({
      success: true,
      imageUrl,
      size: finalSize,
      aspectRatio,
      prompt,
      description: descriptionText,
    });
  } catch (err: any) {
    console.error("Error in /api/generate-image:", err);
    return res.status(500).json({
      error: err.message || "Failed to generate high quality image",
    });
  }
});

// Appointment Booking API Endpoint
app.post("/api/book-appointment", async (req, res) => {
  try {
    const {
      serviceId,
      serviceName,
      doctorId,
      doctorName,
      date,
      timeSlot,
      patientName,
      patientPhone,
      patientEmail,
      notes,
    } = req.body || {};

    const required = { serviceId, serviceName, doctorId, doctorName, date, timeSlot, patientName, patientPhone, patientEmail };
    for (const [key, value] of Object.entries(required)) {
      if (!value || typeof value !== "string" || !value.trim()) {
        return res.status(400).json({ error: `Missing required field: ${key}` });
      }
    }

    if (!/^\S+@\S+\.\S+$/.test(patientEmail)) {
      return res.status(400).json({ error: "Invalid email address" });
    }

    if (await isSlotTaken(doctorId, date, timeSlot)) {
      return res.status(409).json({ error: "That time slot is already booked. Please choose another." });
    }

    const randomNum = Math.floor(100000 + Math.random() * 900000);
    const booking = {
      bookingId: `PDC-${randomNum}`,
      serviceId,
      serviceName,
      doctorId,
      doctorName,
      date,
      timeSlot,
      patientName,
      patientPhone,
      patientEmail,
      notes: typeof notes === "string" ? notes : undefined,
      createdAt: new Date().toISOString(),
    };

    await insertBooking(booking);
    await sendBookingEmails({ ...booking, status: "confirmed" });

    return res.json({ success: true, booking: { ...booking, status: "confirmed" } });
  } catch (err: any) {
    console.error("Error in /api/book-appointment:", err);
    return res.status(500).json({ error: err.message || "Failed to book appointment" });
  }
});

// Patient self-service: look up a booking by ID + phone
app.post("/api/bookings/find", async (req, res) => {
  try {
    const { bookingId, patientPhone } = req.body || {};
    if (!bookingId || !patientPhone) {
      return res.status(400).json({ error: "Booking ID and phone number are required" });
    }

    const booking = await findBooking(bookingId, patientPhone);
    if (!booking) {
      return res.status(404).json({ error: "No booking found with that ID and phone number" });
    }

    return res.json({ success: true, booking });
  } catch (err: any) {
    console.error("Error in /api/bookings/find:", err);
    return res.status(500).json({ error: err.message || "Failed to look up booking" });
  }
});

// Patient self-service: reschedule a booking
app.post("/api/bookings/:bookingId/reschedule", async (req, res) => {
  try {
    const { bookingId } = req.params;
    const { patientPhone, date, timeSlot } = req.body || {};

    if (!patientPhone || !date || !timeSlot) {
      return res.status(400).json({ error: "Phone number, date, and time slot are required" });
    }

    const booking = await findBooking(bookingId, patientPhone);
    if (!booking) {
      return res.status(404).json({ error: "No booking found with that ID and phone number" });
    }

    if (booking.status === "cancelled") {
      return res.status(409).json({ error: "This booking has been cancelled and can't be rescheduled" });
    }

    if (await isSlotTaken(booking.doctorId, date, timeSlot, bookingId)) {
      return res.status(409).json({ error: "That time slot is already booked. Please choose another." });
    }

    await rescheduleBooking(bookingId, date, timeSlot);
    return res.json({ success: true, booking: { ...booking, date, timeSlot } });
  } catch (err: any) {
    console.error("Error in /api/bookings/:bookingId/reschedule:", err);
    return res.status(500).json({ error: err.message || "Failed to reschedule booking" });
  }
});

// Patient self-service: cancel a booking
app.post("/api/bookings/:bookingId/cancel", async (req, res) => {
  try {
    const { bookingId } = req.params;
    const { patientPhone } = req.body || {};

    if (!patientPhone) {
      return res.status(400).json({ error: "Phone number is required" });
    }

    const booking = await findBooking(bookingId, patientPhone);
    if (!booking) {
      return res.status(404).json({ error: "No booking found with that ID and phone number" });
    }

    if (booking.status === "cancelled") {
      return res.status(409).json({ error: "This booking is already cancelled" });
    }

    await cancelBooking(bookingId);
    return res.json({ success: true, booking: { ...booking, status: "cancelled" } });
  } catch (err: any) {
    console.error("Error in /api/bookings/:bookingId/cancel:", err);
    return res.status(500).json({ error: err.message || "Failed to cancel booking" });
  }
});

// Admin: list all bookings (demo-only, no auth)
app.get("/api/bookings", async (_req, res) => {
  try {
    return res.json({ success: true, bookings: await listBookings() });
  } catch (err: any) {
    console.error("Error in /api/bookings:", err);
    return res.status(500).json({ error: err.message || "Failed to list bookings" });
  }
});

export default app;
